#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sun Mar  8 21:11:51 2009

import wx

# begin wxGlade: extracode
### this isn't for RunTests, but I need the code
import utility_forgen
# end wxGlade



class rr_MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: rr_MainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.clear = wx.Button(self, -1, "Disable All")
        self.check = wx.Button(self, -1, "Enable All")
        self.execute = wx.Button(self, -1, "Run Tests")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.handle_disabletests, self.clear)
        self.Bind(wx.EVT_BUTTON, self.handle_enabletests, self.check)
        self.Bind(wx.EVT_BUTTON, self.handle_execute, self.execute)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: rr_MainFrame.__set_properties
        self.SetTitle("Regression Test Runner")
        self.clear.SetToolTipString("Clear all selected tests")
        self.check.SetToolTipString("Enable all tests")
        self.execute.SetBackgroundColour(wx.Colour(152, 255, 143))
        self.execute.SetToolTipString("Running selected tests")
        self.execute.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: rr_MainFrame.__do_layout
        root_sizer = wx.BoxSizer(wx.VERTICAL)
        button_sizer = wx.BoxSizer(wx.HORIZONTAL)
        magic_checkbox_sizer = wx.BoxSizer(wx.VERTICAL)
### NOT GENERATED
        utility_forgen.add_dynamic_checkboxes(self, magic_checkbox_sizer)
### /NOT GENERATED
        root_sizer.Add(magic_checkbox_sizer, 1, wx.EXPAND, 0)
        button_sizer.Add(self.clear, 0, wx.ALL, 5)
        button_sizer.Add(self.check, 0, wx.ALL, 5)
        button_sizer.Add(self.execute, 0, wx.ALL, 5)
        root_sizer.Add(button_sizer, 1, wx.EXPAND, 0)
        self.SetSizer(root_sizer)
        root_sizer.Fit(self)
        self.Layout()
        # end wxGlade

    def handle_disabletests(self, event): # wxGlade: rr_MainFrame.<event_handler>
        print "Event handler `handle_disabletests' not implemented!"
        event.Skip()

    def handle_enabletests(self, event): # wxGlade: rr_MainFrame.<event_handler>
        print "Event handler `handle_enabletests' not implemented!"
        event.Skip()

    def handle_execute(self, event): # wxGlade: rr_MainFrame.<event_handler>
        print "Event handler `handle_execute' not implemented!"
        event.Skip()

# end of class rr_MainFrame


class rr_generatedapp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        MainWindow = rr_MainFrame(None, -1, "")
        self.SetTopWindow(MainWindow)
        MainWindow.Show()
        return 1

# end of class rr_generatedapp

if __name__ == "__main__":
    rr_generated = rr_generatedapp(0)
    rr_generated.MainLoop()
